server:
  port: 8080

spring:
    datasource:
        name: das
        url: jdbc:mysql://127.0.0.1:3306/das?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.it611.das.domain

#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql

couchdb:
  ip: http://localhost
  port: :5984
  db: /mychannel
  cc: /asset02


#fabric:
#  cc:
#    name: asset002
#    version: 0.2
#    channel_name: mychannel
#  org:
#    org1:
#      name: org1
#      mspid: org1MSP
#        peer0:
#          name: peer0org1
#          location: grpc://localhost:7051
#        peer1:
#          name: peer1org1
#          location: grpc://localhost:7051
#        order:
#          location: grpc://localhost:7050
#        ca_location: http://localhost:7054
#        Admin:
#          name: Admin
#        User:
#          name: User1
#          mspid: Org1MSP
#
#    org2:
#      name: org2
#      mspid: org2MSP
#        peer0:
#          name: peer0org2
#          location: grpc://localhost:7051
#        peer1:
#          name: peer1org2
#          location: grpc://localhost:7051
#        order:
#          location: grpc://localhost:7050
#        ca_location: http://localhost:7054
#        Admin:
#          name: Admin
#        User:
#          name: User1
#          mspid: Org2MSP
